### PR TITLE
Rework implementation and add support for other CDN types

### PR DESCRIPTION
**Pull request by NeoLegends**
We noticed the official implementation was lacking in some areas. We ended up almost rewriting the whole plugin to be able to support other CDN types other than stories. During the process we also cleaned the code a little.

I've got a support ticket with you pending about the datasource entries on your CDN and we will update the plugin once there is a decision from your side (whether to extend your API or leave it as is and let the user specify the datasources to load, like we do it now).

If you prefer to stay with npm for package management (and not use yarn), that's okay, too. Just tell us and we'll revert that commit. :)

----

The plugin now supports sourcing from tags and datasource entries as well, not only from stories. It creates new GraphQL "entities" (or databases, or whatever) you can query.

Tags:
```graphql
allStoryblokTag {
  edges {
    node {
      id
      name
      tagging_count
    }
  }
}
```

Data Source Entries:
```graphql
allStoryblokDataSourceEntry {
  edges {
    node {
      id
      name
      value
      data_source
    }
  }
}
```

To be able to query data sources, the plugin needs to know which ones to load. As there is no API endpoint on the CDN API that will give you all available data sources, the developer has to specify the data sources to load through the config like this (this is what I meant with the support ticket):

```js
{
  resolve: 'gatsby-source-storyblok',
  options: {
    dataSources: ['data-source-1', 'data-source-2', 'data-source-3'],
    // ... more config
  }
},
```

### CODE REVIEW

**Comment by onefriendaday** [comment]
Hi!

Thanks for the PR. Does it have a specific reason why you removed storyblok-react as a dependency?

Cheers,
Alex

**Comment by NeoLegends** [comment]
As far as I can see, the plugin doesn't require it anywhere in the code.

**Comment by NeoLegends** [comment]
The `bluebird` dependency was removed because node natively supports promises since 4.9 and that's long deprecated by now. :)

**Comment by onefriendaday** [comment]
I see. storyblok-react has been added to the plugin because it is required for the react components to make them editable. It could be installed separately in the project but I think it makes sense to deliver it together with the plugin.

Example component:
~~~
import SbEditable from 'storyblok-react'
const Teaser = (props) => (
  <SbEditable content={props.blok}>
 ...
  </SbEditable>
)
~~~

**Comment by NeoLegends** [comment]
Right, I've been using the boilerplate project (see the other PR) and yeah, its heavily used there. 

However, declaring it as dependency is not the proper way to go here. If you ship `storyblok-react` as a direct dependency you might be causing version conflicts with people that actively install that. Usually, things like this are declared as peer dependency. This way, `npm` / `yarn` don't automatically install them, but warn the user if they're missing. I can re-add `storyblok-react` as a peer dep, are you ok with that?

**Comment by onefriendaday** [comment]
Declaring it as peer dependency sounds good.

**Comment by NeoLegends** [comment]
🎉

**Pull request merged**
