### PR TITLE
chore/peer-deps

### PR DESCRIPTION
**Pull request by PaulieScanlon**
Hi team, hope you're well!

I'm writing a post about Gatsby plugins and will be adding this plugin to my list of super cool plugins. I had a quick peek into your peer deps and noticed Gatsby wasn't listed. 

I've not 100% tested this but looking at `gatsby-node` it looks like the only Gatsby method you're using is `sourceNodes` which is supported all the way back to versions 2 so i think the peer deps i've added to this PR will be fine. 

Lemme know if you'd like me to make any changes. 

Cheers

Paul

### CODE REVIEW

**Comment by schabibi1** [comment]
Hi @PaulieScanlon 👋 My apologies for not getting back to you sooner.

Thanks for the heads-up and it's a good point. We'd like to consider merging your PR and there's one thing I'd like to ask you to change.
I see that `storyblok-react` is added as a peer dependency for the editable feature. We updated to use `storyblok-editable` to follow what React 18 announced to deprecate findDOMNode that is used in `storyblok-react` .

- storyblok-editable: [https://github.com/storyblok/storyblok-editable](https://github.com/storyblok/storyblok-editable)

**Comment by PaulieScanlon** [comment]
Hey @schabibi1 👋 

Do you know which version of `storyblok-editable` should be added as a peer dep? 

If you can let me know the version number i'll update this PR.

**Comment by schabibi1** [comment]
Hi @PaulieScanlon !
We recommend v1.1.0 to use for [storyblok-editable](https://github.com/storyblok/storyblok-editable) (and this is the newest version.)

Thanks a lot for double-checking with us and contributing.

**Review by christianzoppi — APPROVED** [review]

**Pull request merged**
