### PR TITLE
Feature/corejs3 support

### PR DESCRIPTION
**Pull request by heresandyboy**
Users of this library are unable to run or build using gatsby due to an old version of ```storyblok-js-client```. 
The old version results in compatibility issues between core-js 2 and 3, breaking changes in v3 result in errors like:

```Cannot find module 'core-js/modules/es6.regexp.split'```

Latest version of storyblok-js-client uses ```@babel/runtime-corejs3``` which seems to fix the build issues.

I have bumped the versions of any out of date deps to latest.

I have tested this PR using an npm linked version of my branch against [gatsby-storyblok-boilerplate](https://github.com/storyblok/gatsby-storyblok-boilerplate)

I can confirm it fixes the following github issues:
- gatsby-source-storyblok #27 
- [gatsby-storyblok-boilerplate 12](https://github.com/storyblok/gatsby-storyblok-boilerplate/issues/12) (I will update the dependencies on that repo, to pull in the fix, after this is merged)

### CODE REVIEW

**Comment by heresandyboy** [comment]
Hi @DominikAngerer
 I've noticed that the activity on a lot of your repositories - especially the various boilerplates and third party integrations has been really quiet over the last year or two, and the documentation supporting them could really do with a refresh.
I see a fair few issues and some pull requests across these repos, some of which have been open for months without a response from your team.

Would it be fair to say there are some improvements you and your team could make to reassure new developers assessing your platform. I'd love to see a ramp up of communication, documentation and activity around onboarding new developers for each of the supported stacks.

I'd especially benefit from seeing more activity and better documentation for those wishing to use Gatsby. As it stands I am considering both Gatsby and Nextjs for my project, and even though I'd prefer Gatsby, you seem to have more detailed documentation around Next (and more so with Nuxt/vue) than there is with Gatsby. I could end up leaning towards Next so I'm not left out in the cold with support from your community.

That said, I am happy to contribute my own time to fix issues and produce better documentation around Gatsby. I have been unable to find a repo where I can contribute to your guides and docs. It'd be great if these boilerplates were also the source of the documentation so we can contribute to both in parallel. 
Other teams also consider grouping all the examples and boilerplates into a mono repo along with documentation so they may all benefit from each other. 

I imagine that both the various vue based and React based setup guides may have some overlap where some of the implementation could actually be common between them. So once the boilerplate is set up and running, you could move any instructions that are agnostic of the platform to another guide, as a next step - so they all benefit.

For example, please see the differences between these two guides and it should be obvious that there is additional content in the Nextjs guide that could also benefit the Gatsby guide.

[The Complete Guide to Build a Full Blown Multilanguage Website with Gatsby.js](https://www.storyblok.com/tp/gatsby-multilanguage-website-tutorial)

[The Complete Guide to Build a Full Blown Multilanguage Website with Next.js](https://www.storyblok.com/tp/next-js-react-guide)

Finally, I'd love it if someone could have a look at this PR, it should help new comers trying to follow your Gatsby guide to actually get the code to run :)

**Comment by heresandyboy** [comment]
@onefriendaday @emanuelgsouza 
Hey guys, hope you are well, any chance of finding someone who could have a look over this PR for me?
Thanks.

**Comment by heresandyboy** [comment]
I feel like I'm being a huge pain now, trying to find someone who can take some action on this repo. Maybe @samuells  can help?

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this PR @heresandyboy. Just one thing: could you update the `package-lock.json`? Today I'll review this PR.

**Comment by heresandyboy** [comment]
package-lock sorted, sorry about that I tend to use yarn locally and had checked in the yarn.lock instead previously.

Thanks for picking this up, I will follow up and sort out a PR for gatsby-storyblok-boilerplate once this is pushed out.

**Comment by emanuelgsouza** [comment]
Thank you so much. It's not correct maintain `package-lock.json` and `yarn.lock` together, so, thank you again to remove the `yarn.lock`.

**Comment by heresandyboy** [comment]
Great, yeah I totally agree.
Thanks for that. I'll watch out for the next npm release of this package so I can crack on.

**Pull request merged**
