### PR TITLE
chore/update-readme

### PR DESCRIPTION
**Pull request by PaulieScanlon**
Hi team, great job on the docs!

I started using  Storyblok today in preparation for a stream i'm doing on Thursday with Arisa. 

I noticed there were no examples of how to use Gatsby's File System Routes API with collection routes and had to hunt around a bit to find an example of how do use `content`.

I hope this PR will help others get started  more easily. 

Happy to make any / all changes you suggest ☺️

Thanks in advance

Paul

- add File System Routes API example to README
- add `content` querying with switch statement example to README

### CODE REVIEW

**Comment by schabibi1** [comment]
Hi @PaulieScanlon ! Thanks for letting us know. I reviewed and forwarded your pull request to my colleague @christianzoppi  to have a final review.

Really excited to do a live show with you tomorrow😊

**Comment by christianzoppi** [comment]
Thank you for the great contribution @PaulieScanlon! 😄

**Comment by PaulieScanlon** [comment]
Hey @schabibi1 Ty for this! Yes V excited about tomorrow. Looking forward to meeting you 🥳

**Pull request merged**
